### ISSUE TITLE
Text is invisible

### ISSUE THREAD

**Issue by ghost** [rparkins999/AndroidSecondsClockWidget#6] opened 2022-06-21 17:38 UTC
The text is invisible in light theme but is visible in dark theme. 
![Screenshot_20220621-133040_Seconds_Clock](https://user-images.githubusercontent.com/84468401/174862348-0abc0586-30c2-451b-875e-1022f661fd4d.png) 
![Screenshot_20220621-133742_Seconds_Clock](https://user-images.githubusercontent.com/84468401/174862901-5b2cf0c8-a7bf-497c-b255-8095f8184ea0.png)

**Comment by rparkins999** [comment] 2022-06-22 06:45
Should be fixed in 2.3

**Closed as completed** 2022-07-07 04:56 UTC

**Comment by ghost** [comment] 2022-07-07 04:57
This issue is fixed in the latest version.

**Comment by THEtomaso** [comment] 2023-08-04 16:15
@rparkins999:
> Should be fixed in 2.3

Apparently not.
I tried changing the text colour from white to black in v2.3, and the text became invisible!

**Comment by rparkins999** [comment] 2023-08-04 17:28
If you try to display black text on a black background, of course it will be invisible! The app displays the text on its configuration pages in the device's foreground colour. In light mode you get black text on a white ground. In dark mode you get white text on a black ground. If you set up some strange default colours, many apps won't behave normally.

**Comment by THEtomaso** [comment] 2023-08-04 19:01
Thanks for your quick reply, rparkins999.
I'm indeed using dark mode (stock option).
..but the lock / home screen wallpaper that I'm using has a light colour, so shouldn't black widget text be visible on top of that?
Other widgets that I'm using are able to do this, without any issues.

--

**EDIT:**

@rparkins999:
There's definitely still a bug, because every time I try to configure its background and text colour, the text becomes invisible.
The only way to make it visible again is to clear its app data!

**Comment by rparkins999** [comment] 2023-08-05 21:42
The original issue was about the configuration pages. [THEtomaso](https://github.com/THEtomaso) commented about the _widget_. The widget configuration page allows you to set the widget's background colour and opacity, and the widget's text colour. For the text to be visible, the text colour must differ from the background colour if it has high opacity, or from the colour of the home screen wallpaper if the widget background has low opacity.

There seems to be a problem with installing version 2.3 over a previous version. If you try to change the text colour of a widget created by an earlier version of SecondsClock, the widget does indeed disappear. I think that this is due to a change in the way that the configuration is stored: I thought that I had fixed this so that it would read the old configuration and upgrade it to the new format, but this is of course hard to test. The workaround is to delete the old widget (long press on it, and touch the bin icon), and create a new widget (long press on the app in the app screen and touch the widget icon). Changing the text colour of the new widget works properly. If touching the new widget doesn't bring up its configuration page, run the app, select configure existing widget, touch the widget that you want to configure, and set its touch action.

**Comment by THEtomaso** [comment] 2023-08-05 22:32
> The original issue was about the configuration pages.

The problem occurs there too (invisible text in the preview box).

--

> There seems to be a problem with installing version 2.3 over a previous version.

v2.3 is the first version that I've ever installed (besides, I only perform clean installs anyway).

--

Also, the problem occurs regardlessly, both if I configure an existing widget, or a new one.

--

**EDIT:**

I tried changing to Light mode, but the problem remains, so it's not a Dark-mode-only thing either.

**Comment by rparkins999** [comment] 2023-08-06 05:17
[R] The original issue was about the configuration pages.
[T] The problem occurs there too (invisible text in the preview box).

Text in the preview box is the _widget_. Please look again at the screenshots. The invisible text is the labels on the checkboxes, not the widget. If the widget display on the configuration page is incorrect, this is an entirely different problem. SecondsClock uses default colours for the labels on the checkboxes, but explicitly sets the colours and opacity on the actual widget, and also on the widget preview to show how it would look on your home screen.

[R] There seems to be a problem with installing version 2.3 over a previous version.
[T] v2.3 is the first version that I've ever installed (besides, I only perform clean installs anyway).
[T] Also, the problem occurs regardlessly, both if I configure an existing widget, or a new one.

I was able to reproduce the failure to display an old actual widget correctly if I modified its text colour, but the preview widget on the configuration pages _was_ displayed correctly. Deleting the widget and creating a new one caused both the preview and the actual widget to be displayed correctly.

I think there must be some issue with your device configuration or with the build that you have installed. I need more information to try and investigate this since I can't reproduce on my phone what you describe. Did you install from the github release, or from f-droid, or from a build that you made yourself from the github sources? I need to see the build info at the top of the page that you see when you touch the app (not the widget), and also screenshots of the whole configuration pages for text colour and background colour. If you don't know how to get screenshots, please consult your device's user manual. I also need to know what device you are running on, and what software version it is running. If you have more than one Android device, or you know someone with a different Android device who is willing to install SecondsClock, does another device show the same behaviour? Has your Android device received a software update recently? Software updates should not break applications, but my experience is that they often do.

**Comment by THEtomaso** [comment] 2023-08-06 13:19
Thanks for looking into this, rparkins999! 👍 

--

> If the widget display on the configuration page is incorrect, this is an entirely different problem.

This seems to be erratic for me.
Sometimes, the preview works, and the text is shown in the preview box, after I've changed it.
..but then, when exiting and re-entering the app, it's invisible.
In either case, the text is invisible on the actual widget.
Even if I change the background to full opacity (different than the text colour, of course), the text still remains invisible!

--

> Did you install from the github release, or from f-droid, or from a build that you made yourself from the github sources?

From your GitHub repo's releases.

--

> I need to see the build info at the top of the page that you see when you touch the app

It says "2.3 built Wed Jun 22 07:33:06 BST 2022".

--

> I also need to know what device you are running on, and what software version it is running.

* Device: Samsung Galaxy XCover 4s
* Android version: 11
* Samsung One UI version: 3.1

--

> and also screenshots of the whole configuration pages for text colour and background colour.

Here are some screenshots (except from changing the text colour to black, all setting are default):

![SecondsClock-config-background](https://github.com/rparkins999/AndroidSecondsClock/assets/9382674/e2830a89-81ff-4587-8247-1ab622e31700)

![SecondsClock-config-text](https://github.com/rparkins999/AndroidSecondsClock/assets/9382674/3fa3b411-353b-4115-a43a-ad12697f898b)

![SecondsClock-homescreen-pfbg_1](https://github.com/rparkins999/AndroidSecondsClock/assets/9382674/e349d7b0-e6f3-467e-aefa-4dffbd022410)

![SecondsClock-homescreen-pfbg_2](https://github.com/rparkins999/AndroidSecondsClock/assets/9382674/c4cc9d4c-1d5d-4227-9b67-42bca2a88762)

![SecondsClock-homescreen-whitebg](https://github.com/rparkins999/AndroidSecondsClock/assets/9382674/2ab5504f-f0c9-4b15-abc5-0d9fd9825e84)

**Comment by rparkins999** [comment] 2023-08-06 15:14
I've moved this discussion to a new issue 12, since the original issue referring to the checkbox labels was fixed. I think that I have a consistent way of making it fail now.
